# Generated by Django 4.0 on 2023-11-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Associacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(max_length=254)),
                ('razao_social', models.CharField(max_length=254)),
                ('cnpj', models.BigIntegerField()),
                ('telefone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('presidente', models.CharField(max_length=254)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
