# Generated by Django 4.2.4 on 2023-09-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associacao',
            name='cnpj',
            field=models.BigIntegerField(),
        ),
    ]
