# Generated by Django 4.2.4 on 2023-09-19 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jornalistas', '0001_initial'),
        ('obras', '0001_initial'),
        ('opcoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jornalista',
            name='cidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='opcoes.cidades'),
        ),
        migrations.AddField(
            model_name='jornalista',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='opcoes.estados'),
        ),
        migrations.AddField(
            model_name='jornalista',
            name='estado_civil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='opcoes.estadocivil'),
        ),
        migrations.AddField(
            model_name='jornalista',
            name='genero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='opcoes.genero'),
        ),
        migrations.AddField(
            model_name='jornalista',
            name='historico_profissional',
            field=models.ManyToManyField(to='jornalistas.historicoprofissional'),
        ),
        migrations.AddField(
            model_name='jornalista',
            name='obras_jornalisticas',
            field=models.ManyToManyField(to='obras.obrajornalistica'),
        ),
    ]
