# Generated by Django 4.2.4 on 2023-08-23 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('revisores', '0001_initial'),
        ('jornalistas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicoprofissional',
            name='revisor_responsavel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='revisores.revisor'),
        ),
    ]
