# Generated by Django 4.0 on 2023-11-08 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jornalistas', '0001_initial'),
        ('opcoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jornalista',
            name='estado_civil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='opcoes.estadocivil'),
        ),
        migrations.AddField(
            model_name='jornalista',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='opcoes.genero'),
        ),
    ]
