# Generated by Django 4.2.4 on 2023-09-19 03:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jornalistas', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('revisores', '0001_initial'),
        ('opcoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jornalista',
            name='revisor_responsavel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='revisores.revisor'),
        ),
        migrations.AddField(
            model_name='jornalista',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicoprofissional',
            name='revisor_responsavel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='revisores.revisor'),
        ),
        migrations.AddField(
            model_name='historicoprofissional',
            name='veiculo_de_comunicacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='opcoes.veiculodecomunicacao'),
        ),
    ]
