# Generated by Django 4.0 on 2023-11-08 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jornalistas', '0002_initial'),
        ('revisores', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('opcoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jornalista',
            name='revisor_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='revisores.revisor'),
        ),
        migrations.AddField(
            model_name='jornalista',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.AddField(
            model_name='historicoprofissional',
            name='jornalista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jornalistas.jornalista'),
        ),
        migrations.AddField(
            model_name='historicoprofissional',
            name='veiculo_de_comunicacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='opcoes.veiculodecomunicacao'),
        ),
        migrations.AddField(
            model_name='diploma',
            name='jornalista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jornalistas.jornalista'),
        ),
    ]
