# Generated by Django 4.2.4 on 2023-09-19 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jornalistas', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicoprofissional',
            name='revisor_responsavel',
        ),
        migrations.RemoveField(
            model_name='historicoprofissional',
            name='validado',
        ),
    ]
