# Generated by Django 4.2.4 on 2023-08-23 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornalistas', '0003_jornalista_diploma_jornalista_revisor_responsavel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jornalista',
            name='diploma',
            field=models.ImageField(upload_to=None),
        ),
    ]
