# Generated by Django 4.2.4 on 2023-09-22 12:14

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0001_initial'),
        ('opcoes', '0001_initial'),
        ('jornalistas', '0004_remove_historicoprofissional_revisor_responsavel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jornalista',
            name='cidade',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='estado', chained_model_field='estado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, sort=False, to='opcoes.cidades'),
        ),
        migrations.AlterField(
            model_name='jornalista',
            name='data_de_nascimento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='jornalista',
            name='historico_profissional',
            field=models.ManyToManyField(blank=True, to='jornalistas.historicoprofissional'),
        ),
        migrations.AlterField(
            model_name='jornalista',
            name='obras_jornalisticas',
            field=models.ManyToManyField(blank=True, to='obras.obrajornalistica'),
        ),
        migrations.AlterField(
            model_name='jornalista',
            name='telefone',
            field=models.CharField(max_length=50),
        ),
    ]
