# Generated by Django 4.2.4 on 2023-09-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornalistas', '0005_alter_jornalista_cidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jornalista',
            name='cpf',
            field=models.CharField(max_length=14),
        ),
    ]
