# Generated by Django 4.2.4 on 2023-09-22 13:14

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('opcoes', '0001_initial'),
        ('jornalistas', '0006_alter_jornalista_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jornalista',
            name='cidade',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='estado', chained_model_field='estado', on_delete=django.db.models.deletion.DO_NOTHING, sort=False, to='opcoes.cidades'),
        ),
        migrations.AlterField(
            model_name='jornalista',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='opcoes.estados'),
        ),
        migrations.AlterField(
            model_name='jornalista',
            name='estado_civil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='opcoes.estadocivil'),
        ),
        migrations.AlterField(
            model_name='jornalista',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='opcoes.genero'),
        ),
        migrations.AlterField(
            model_name='jornalista',
            name='registro',
            field=models.CharField(max_length=50),
        ),
    ]
