# Generated by Django 4.2.4 on 2023-10-18 12:12

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('revisores', '0001_initial'),
        ('opcoes', '0001_initial'),
        ('jornalistas', '0007_alter_jornalista_cidade_alter_jornalista_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jornalista',
            name='historico_profissional',
        ),
        migrations.AddField(
            model_name='historicoprofissional',
            name='jornalista',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='jornalistas.jornalista'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jornalista',
            name='cidade',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='estado', chained_model_field='estado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, sort=False, to='opcoes.cidades'),
        ),
        migrations.AlterField(
            model_name='jornalista',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='opcoes.estados'),
        ),
        migrations.AlterField(
            model_name='jornalista',
            name='revisor_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='revisores.revisor'),
        ),
    ]
