# Generated by Django 4.2.4 on 2023-10-18 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jornalistas', '0008_remove_jornalista_historico_profissional_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jornalista',
            name='obras_jornalisticas',
        ),
    ]
