# Generated by Django 4.2.4 on 2023-10-25 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opcoes', '0001_initial'),
        ('associacoes', '0003_remove_associacao_ddd_telefone_and_more'),
        ('revisores', '0001_initial'),
        ('jornalistas', '0010_remove_jornalista_cidade_remove_jornalista_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicoprofissional',
            name='veiculo_de_comunicacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='opcoes.veiculodecomunicacao'),
        ),
        migrations.RemoveField(
            model_name='jornalista',
            name='associacao',
        ),
        migrations.AlterField(
            model_name='jornalista',
            name='estado_civil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='opcoes.estadocivil'),
        ),
        migrations.AlterField(
            model_name='jornalista',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='opcoes.genero'),
        ),
        migrations.AlterField(
            model_name='jornalista',
            name='revisor_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='revisores.revisor'),
        ),
        migrations.AddField(
            model_name='jornalista',
            name='associacao',
            field=models.ManyToManyField(blank=True, to='associacoes.associacao'),
        ),
    ]
