# Generated by Django 4.2.4 on 2023-10-25 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jornalistas', '0011_alter_historicoprofissional_veiculo_de_comunicacao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jornalista',
            old_name='associacao',
            new_name='associacoes',
        ),
    ]
