# Generated by Django 4.2.4 on 2023-10-26 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jornalistas', '0012_rename_associacao_jornalista_associacoes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicoprofissional',
            old_name='data_de_termino',
            new_name='data_termino',
        ),
    ]
