# Generated by Django 4.2.4 on 2023-10-26 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornalistas', '0013_rename_data_de_termino_historicoprofissional_data_termino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jornalista',
            name='diploma',
            field=models.ImageField(upload_to='diplomas/%Y/%m/%d/'),
        ),
    ]
