# Generated by Django 4.1.4 on 2023-10-27 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornalistas', '0014_alter_jornalista_diploma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jornalista',
            name='telefone',
            field=models.IntegerField(max_length=50),
        ),
    ]
