# Generated by Django 4.1.4 on 2023-10-27 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornalistas', '0015_alter_jornalista_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jornalista',
            name='telefone',
            field=models.TextField(max_length=50),
        ),
    ]
