# Generated by Django 4.0 on 2023-11-03 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('associacoes', '0004_alter_associacao_telefone'),
        ('jornalistas', '0016_alter_jornalista_telefone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jornalista',
            name='diploma',
        ),
        migrations.AlterField(
            model_name='jornalista',
            name='associacoes',
            field=models.ManyToManyField(blank=True, to='associacoes.Associacao'),
        ),
        migrations.AlterField(
            model_name='jornalista',
            name='telefone',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Diploma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diploma', models.ImageField(upload_to='diplomas/%Y/%m/%d/')),
                ('jornalista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jornalistas.jornalista')),
            ],
        ),
    ]
