# Generated by Django 4.0 on 2023-11-03 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornalistas', '0017_remove_jornalista_diploma_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diploma',
            old_name='diploma',
            new_name='arquivo',
        ),
        migrations.AddField(
            model_name='diploma',
            name='descricao',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jornalista',
            name='registro',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
