# Generated by Django 4.2.4 on 2023-10-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associacoes', '0003_remove_associacao_ddd_telefone_and_more'),
        ('revisores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revisor',
            name='associacao',
        ),
        migrations.AddField(
            model_name='revisor',
            name='associacao',
            field=models.ManyToManyField(blank=True, to='associacoes.associacao'),
        ),
    ]
