# Generated by Django 4.2.4 on 2023-10-25 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revisores', '0002_remove_revisor_associacao_revisor_associacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='revisor',
            old_name='associacao',
            new_name='associacoes',
        ),
    ]
