# Generated by Django 4.0 on 2023-11-03 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associacoes', '0004_alter_associacao_telefone'),
        ('revisores', '0003_rename_associacao_revisor_associacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revisor',
            name='associacoes',
            field=models.ManyToManyField(blank=True, to='associacoes.Associacao'),
        ),
    ]
