# Generated by Django 4.2.8 on 2024-07-27 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associacao',
            name='cnpj',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='associacao',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='associacao',
            name='nome_fantasia',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='associacao',
            name='presidente',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='associacao',
            name='razao_social',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='associacao',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
