# Generated by Django 4.2.4 on 2023-12-06 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historico_profissional', '0002_historicoprofissional_tipo_de_veiculo_and_more'),
        ('obras', '0002_alter_publicao_obra_jornalistica_alter_publicao_tipo_and_more'),
        ('opcoes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculodecomunicacao',
            name='tipo_de_veiculo',
        ),
        migrations.DeleteModel(
            name='TipoDeVeiculo',
        ),
        migrations.DeleteModel(
            name='VeiculoDeComunicacao',
        ),
    ]
