# Generated by Django 4.0 on 2023-11-03 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opcoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redessociais',
            name='link',
            field=models.URLField(max_length=254),
        ),
    ]
