# Generated by Django 4.2.4 on 2023-08-23 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opcoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDePublicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=64)),
            ],
        ),
    ]
