# Generated by Django 4.2.4 on 2023-08-23 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='ano_publicacao',
        ),
    ]
