# Generated by Django 4.2.4 on 2023-08-23 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opcoes', '0002_tipodepublicacao'),
        ('obras', '0002_remove_livro_ano_publicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicao',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='opcoes.tipodepublicacao'),
        ),
        migrations.DeleteModel(
            name='TipoDePublicacao',
        ),
    ]
