# Generated by Django 4.0 on 2023-11-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('associacoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diploma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('arquivo', models.ImageField(upload_to='diplomas/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoProfissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=254)),
                ('cargo', models.CharField(max_length=254)),
                ('data_inicio', models.DateField()),
                ('data_termino', models.DateField(blank=True, null=True)),
                ('referencia', models.CharField(max_length=254)),
                ('contato_da_referencia', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Jornalista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_de_guerra', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=255)),
                ('sobrenome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14)),
                ('data_de_nascimento', models.DateField()),
                ('telefone', models.CharField(max_length=50)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='')),
                ('registro', models.CharField(blank=True, max_length=50, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aprovado', models.BooleanField(default=False)),
                ('associacoes', models.ManyToManyField(blank=True, to='associacoes.Associacao')),
            ],
        ),
    ]
