# Generated by Django 4.0 on 2023-11-10 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornalistas', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jornalista',
            name='ddd',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jornalista',
            name='ddi',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jornalista',
            name='telefone',
            field=models.IntegerField(),
        ),
    ]
