# Generated by Django 4.0 on 2023-11-10 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jornalistas', '0004_jornalista_ddd_jornalista_ddi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicoprofissional',
            name='contato_da_referencia',
        ),
        migrations.RemoveField(
            model_name='historicoprofissional',
            name='referencia',
        ),
        migrations.CreateModel(
            name='Referencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=254)),
                ('contato', models.CharField(max_length=254)),
                ('historico_profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jornalistas.historicoprofissional')),
            ],
        ),
    ]
