# Generated by Django 4.0 on 2023-12-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornalistas', '0006_remove_referencia_historico_profissional_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jornalista',
            name='cpf',
            field=models.IntegerField(),
        ),
    ]
