# Generated by Django 4.0 on 2023-12-03 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornalistas', '0007_alter_jornalista_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jornalista',
            name='ddd',
        ),
        migrations.AlterField(
            model_name='jornalista',
            name='cpf',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='jornalista',
            name='ddi',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='jornalista',
            name='telefone',
            field=models.CharField(max_length=11),
        ),
    ]
