# Generated by Django 4.0 on 2023-12-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornalistas', '0008_remove_jornalista_ddd_alter_jornalista_cpf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jornalista',
            name='show_associacoes',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jornalista',
            name='show_cpf',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jornalista',
            name='show_data_de_nascimento',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jornalista',
            name='show_ddi',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jornalista',
            name='show_estado_civil',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jornalista',
            name='show_foto',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jornalista',
            name='show_genero',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jornalista',
            name='show_nome',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jornalista',
            name='show_nome_de_guerra',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jornalista',
            name='show_registro',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jornalista',
            name='show_sobrenome',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jornalista',
            name='show_telefone',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
