# Generated by Django 4.2.4 on 2023-12-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornalistas', '0009_jornalista_show_associacoes_jornalista_show_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jornalista',
            name='show_associacoes',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='jornalista',
            name='show_cpf',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='jornalista',
            name='show_data_de_nascimento',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='jornalista',
            name='show_ddi',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='jornalista',
            name='show_estado_civil',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='jornalista',
            name='show_foto',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='jornalista',
            name='show_genero',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='jornalista',
            name='show_nome',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='jornalista',
            name='show_nome_de_guerra',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='jornalista',
            name='show_registro',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='jornalista',
            name='show_sobrenome',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='jornalista',
            name='show_telefone',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
