# Generated by Django 4.2.8 on 2024-07-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornalistas', '0011_jornalista_curriculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diploma',
            name='arquivo',
            field=models.ImageField(blank=True, null=True, upload_to='diplomas/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='diploma',
            name='descricao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
