# Generated by Django 4.2.8 on 2024-07-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornalistas', '0012_alter_diploma_arquivo_alter_diploma_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='jornalista',
            name='funcao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
