# Generated by Django 4.2.8 on 2024-07-30 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornalistas', '0013_jornalista_funcao'),
    ]

    operations = [
        migrations.AddField(
            model_name='jornalista',
            name='show_funcao',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
