# Generated by Django 4.2.8 on 2024-08-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornalistas', '0016_jornalista_show_cidade_jornalista_show_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='jornalista',
            name='minibio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
