# Generated by Django 4.0 on 2023-11-10 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opcoes', '0001_initial'),
        ('jornalistas', '0006_remove_referencia_historico_profissional_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoProfissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=254)),
                ('cargo', models.CharField(max_length=254)),
                ('data_inicio', models.DateField()),
                ('data_termino', models.DateField(blank=True, null=True)),
                ('jornalista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jornalistas.jornalista')),
                ('veiculo_de_comunicacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='opcoes.veiculodecomunicacao')),
            ],
        ),
        migrations.CreateModel(
            name='Referencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=254)),
                ('contato', models.CharField(max_length=254)),
                ('historico_profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='historico_profissional.historicoprofissional')),
            ],
        ),
    ]
