# Generated by Django 4.2.4 on 2023-12-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historico_profissional', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicoprofissional',
            name='tipo_de_veiculo',
            field=models.CharField(default=1, max_length=55),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicoprofissional',
            name='veiculo_de_comunicacao',
            field=models.CharField(max_length=55),
        ),
    ]
